---
- name: Configure nexus
  hosts: nexus
  roles:
    - role: nexus3-oss
      when: ansible_env.SERVICE_CONFIG_NEXUS_ENABLE is defined and ansible_env.SERVICE_CONFIG_NEXUS_ENABLE == "true"

- name: Configure gitlab
  hosts: gitlab
  roles:
    - role: gitlab-config
      when: ansible_env.SERVICE_CONFIG_GITLAB_ENABLE is defined and ansible_env.SERVICE_CONFIG_GITLAB_ENABLE == "true"
