#!/bin/bash
#
# REGISTRY_URL
# REGISTRY_USERNAME
# REGISTRY_PASSWORD
set -e

REGISTRY_URL=${REGISTRY_URL:-http://nexus/nexus/repository/docker-build/}
REGISTRY_USERNAME=${REGISTRY_USERNAME:? REGISTRY_USERNAME not defined }
REGISTRY_PASSWORD=${REGISTRY_PASSWORD:? REGISTRY_PASSWORD not defined}

PACKAGENAME=${1:? $(basename $0) PACKAGENAME VERSION needed}
VERSION=${2:? $(basename $0) PACKAGENAME VERSION needed}
LONG_PACKAGENAME=${PACKAGENAME}-${VERSION}
FILENAME=${LONG_PACKAGENAME}.tar.gz
PACKAGEDIR=dist

[ -f $PACKAGEDIR/$FILENAME ] || exit 1

curl -LS -u $REGISTRY_USERNAME:$REGISTRY_PASSWORD --upload-file $PACKAGEDIR/$FILENAME  $REGISTRY_URL/${PACKAGENAME}/${VERSION}/$FILENAME
echo $?
